### ISSUE TITLE
Use for yeast genome

### ISSUE THREAD

**Issue by emmannaemeka** [JanaSperschneider/FindTelomeres#1]
Hi Can this be used for Yeast genome? I ran it on the reference genome of my yeast but no telomeric repeat found. How can it be adapted for yeast?

**Comment by JanaSperschneider** [comment]
Hi, 

I suspect your yeast species has a different type of telomeric repeat than the one used in the script. You can look here: http://telomerase.asu.edu/sequences_telomere.html or inspect the start and end of your chromosomes to find the appropriate repeat type.

The script currently searches only for telomereas of the type TTAGGG/CCCTAA. You can change the regular expression in the script to search for other telomeric repeats. Look at line 25, it has this: TELOMERES = ["C{2,4}T{1,2}A{1,3}", "T{1,3}A{1,2}G{2,4}"]. You can change it to the type of repeat that occurs in yeast.

Thanks, 
Jana

**Comment by Astahlke** [comment]
Hi Jana, 

Similar question here. I want to look for an alternative motif, TCAGG/AGTCC. My python is rusty and I can't quite figure out how to swap out the regex of line 25. Can you provide some guidance? Thank you!

Amanda

**Comment by JanaSperschneider** [comment]
Hi Amanda,

have a look at line 25, it has this: TELOMERES = ["C{2,4}T{1,2}A{1,3}", "T{1,3}A{1,2}G{2,4}"]

If you want to search for the exact match TCAGG/AGTCC, you can change it to:
TELOMERES = ["TCAGG", "AGTCC"]

If you want a bit of variation allowed, you could use:
TELOMERES = ["T{1,2}C{1,2}A{1,2}G{2,4}", "A{1,2}G{1,2}T{1,2}C{2,4}"]

Hope that works for you!
Jana

**Comment by Astahlke** [comment]
Perfect, thank you!
